# Generated by Django 4.2.20 on 2025-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoprod',
            name='nombreTipoProd',
            field=models.CharField(max_length=60, verbose_name='Nombre del tipo producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechaVenta',
            field=models.DateField(verbose_name='Fecha de venta'),
        ),
    ]
